//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Effort_Tracking_System
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Assign_Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Assign_Task()
        {
            this.Efforts = new HashSet<Effort>();
        }
    
        public int assign_task_id { get; set; }
        [Required(ErrorMessage = "User ID is required.")]
        public Nullable<int> user_id { get; set; }

        [Required(ErrorMessage = "Project ID is required.")]
        public Nullable<int> project_id { get; set; }

        [Required(ErrorMessage = "Task ID is required.")]
        public Nullable<int> task_id { get; set; }

        [Required(ErrorMessage = "Shift ID is required.")]
        public Nullable<int> shift_id { get; set; }

        [Required(ErrorMessage = "Allocated Hours is required.")]
        public int allocated_hours { get; set; }

        [Required(ErrorMessage = "Assignment Date is required.")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> assignmentdate { get; set; }

        [Required(ErrorMessage = "Status is required.")]
        [StringLength(50, ErrorMessage = "Status cannot exceed 50 characters.")]
        public string Status { get; set; }

        public virtual Project Project { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Effort> Efforts { get; set; }
    }
}
