//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Effort_Tracking_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Effort_Tracking_SystemEntities : DbContext
    {
        public Effort_Tracking_SystemEntities()
            : base("name=Effort_Tracking_SystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<effort> efforts { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<shift> shifts { get; set; }
        public virtual DbSet<task> tasks { get; set; }
        public virtual DbSet<unavailability> unavailabilities { get; set; }
        public virtual DbSet<user_task_assignment> user_task_assignment { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
