//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Effort_Tracking_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class effort
    {
        public int effort_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<int> task_id { get; set; }
        public Nullable<int> shift_id { get; set; }
        public int hours_worked { get; set; }
        public System.DateTime date_time { get; set; }
        public string status { get; set; }
    
        public virtual project project { get; set; }
        public virtual shift shift { get; set; }
        public virtual task task { get; set; }
        public virtual user user { get; set; }
    }
}
