//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Effort_Tracking_System
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Xml.Linq;

    public partial class Effort
    {
        public int effort_id { get; set; }

        [Required(ErrorMessage = "Assign Task ID is required.")]
        public Nullable<int> assign_task_id { get; set; }

        [Required(ErrorMessage = "Shift ID is required.")]
        public Nullable<int> shift_id { get; set; }

        [Required(ErrorMessage = "Hours worked is required.")]
        [Range(1, int.MaxValue, ErrorMessage = "Hours worked must be a positive value.")]
        public int hours_worked { get; set; }

        [Required(ErrorMessage = "Date and time is required.")]
        [Display(Name = "Date and Time")]
        public Nullable<System.DateTime> date_time { get; set; }

        [Required(ErrorMessage = "Status is required.")]
        [StringLength(50, ErrorMessage = "Status cannot exceed 50 characters.")]
        public string status { get; set; }

        public virtual Assign_Task Assign_Task { get; set; }
        public virtual Shift Shift { get; set; }
    }
}
