//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Effort_Tracking_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class unavailability
    {
        public int unavailability_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> shift_id { get; set; }
        public string reason { get; set; }
        public string status { get; set; }
    
        public virtual shift shift { get; set; }
        public virtual user user { get; set; }
    }
}
